# This is a basic workflow to help you get started with Actions

name: Build sphinx

# Controls when the action will run. 
on:
- push
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#       - name: Install Python dependencies
#         uses: py-actions/py-dependency-install@v2

      # Runs a single command using the runners shell
      - uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: "pip install pydata-sphinx-theme"
          build-command: "make html -e"
          docs-folder: "docsrc/"
